### PR TITLE
Uploading Codes of 45 days Coding Challenge of ABC 

### PR DESCRIPTION
**Pull request by adityayadavms**
Adding codes of the problem statements given to us as Weekly challenge which is a part of 45 days Coding Challenge of our Adamas Blockchain Club , which consists of codes related to arrays , strings and OOPS .

### CODE REVIEW

**Comment by sandipkumardey** [comment]
Hey @adityayadavms just try adding a descriptive description to this attached PR, just in 2-3lines to make it more clear. Otherwise it's all good! Thanks :)

**Comment by adityayadavms** [comment]
> Hey @adityayadavms just try adding a descriptive description to this attached PR, just in 2-3lines to make it more clear. Otherwise it's all good! Thanks :)

okay  @sandipkumardey

**Comment by sandipkumardey** [comment]
Great merging it! @adityayadavms

**Comment by adityayadavms** [comment]
> Great merging it! @adityayadavms

Okay thank you @sandipkumardey

**Pull request merged**
